version: "2"

services:
  nginx-proxy:
    image: jlesage/nginx-proxy-manager
    container_name: docker-nginx-proxy
    restart: always
    volumes:
      - /docker/appdata/nginx-proxy:/config
    ports:
      - 8181:8181
      - 80:8080
      - 443:4443
    networks:
      connection:
  portainer:
    image: portainer/portainer
    container_name: docker-portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/portainer/data:/data
    networks:
      connection:
  gitlab-runner:
    build: gitlab-runner/
    container_name: docker-gitlab-runner
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /publish:/publish
      - /docker/appdata/gitlab-runner/config:/etc/gitlab-runner
      - /home/gitlab-runner:/home/gitlab-runner:rw

networks:
  connection:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.49.0/24
          gateway: 192.168.49.1

