version: "2"

services:
  nginx-proxy:
    image: jlesage/nginx-proxy-manager
    container_name: docker-nginx-proxy
    restart: unless-stopped
    volumes:
      - /docker/appdata/nginx-proxy:/config
    ports:
      - 8181:8181
      - 80:8080
      - 443:4443
    networks:
      connection:
  portainer:
    image: portainer/portainer
    container_name: docker-portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/portainer/data:/data
    networks:
      connection:
  gitlab-runner:
    build: gitlab-runner/
    container_name: docker-gitlab-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/publish:/home/publish
      - /home/server:/home/server
      - /docker/appdata/gitlab-runner/config:/etc/gitlab-runner
      - /home/gitlab-runner:/home/gitlab-runner:rw
  jenkins: 
    image: jenkins
    container_name: docker-jenkins
    restart: unless-stopped
    volumes:
      - /docker/appdata/jenkins:/var/jenkins_home
    ports:
      - 9011:8080
    networks:
      connection:

networks:
  connection:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.49.0/24
          gateway: 192.168.49.1

